name: 'Codecov ATS'
description: 'GitHub Action that returns selected test labels from Codecov☂️ to CI'
inputs:
  token:
    description: 'Repository upload token - get it from codecov.io. Required or set it with the environment variable CODECOV_TOKEN'
    required: false
  static_token:
    description: 'Repository static token - get it from codecov.io. Required or set it with the environment variable CODECOV_STATIC_TOKEN'
    required: false
  enterprise_url:
    description: 'Change the upload host (Enterprise use only)'
    required: false
  file_pattern:
    description: 'File pattern to search for. Defaults to "*"'
    required: false
  folders_to_exclude:
    description: 'Avoid certain folders when uploading static analysis'
    requred: false
  force:
    description: 'Force upload of files during static analysis regardless if they are new'
    required: false
  label_max_wait_time:
    description: 'Max time (in seconds) to wait for the label analysis. Default is to wait forever.'
    required: false
  os:
    description: 'Override the assumed OS. Options are linux | macos | windows.'
    required: false
  output_variable:
    description: 'Variable to save down tests string. Defaults to CODECOV_ATS_TESTS'
    required: false
  override_base_commit:
    description: 'Override the assumed base commit.'
    required: false
  override_branch:
    description: 'Branch to which this commit belongs to'
    required: false
  override_commit:
    description: 'Commit SHA (with 40 chars)'
    required: false
  override_parent:
    description: 'SHA (with 40 chars) of what should be the parent of this commit'
    required: false
  override_pr:
    description: 'Specify the pull request number mannually.'
    required: false
  override_slug:
    description: 'owner/repo slug used instead of the private repo token in Self-hosted'
    required: false
  static_folders_to_exclude:
    description: 'Folders not to search during static analysis'
    required: false
  static_folder_to_search:
    description: 'Folder to search during static analysis'
    required: false
  static_force:
    description: 'Force running of static analysis'
    required: false
  static_number_processes:
    description: 'Number of processes to use during static analysis'
    required: false
  static_search_pattern:
    description: 'File pattern to search for during static analysis'
    required: false
  verbose:
    description: 'Specify whether the Codecov output should be verbose'
    required: false
  version:
    description: 'Specify which version of the Codecov CLI should be used. Defaults to `latest`'
    required: false


branding:
  color: 'red'
  icon: 'umbrella'

runs:
  using: "composite"
  steps:
    - id: codecov-ats
      run: |
        echo "${{ github.action_path }}" >> $GITHUB_PATH
        echo "Running ATS Action version: $(cat ${{ github.action_path }}/dist/VERSION)"

        ${{ github.action_path }}/dist/codecov_ats.sh | tee codecov_ats_output.txt

        if [[ $? == 0 ]]; then
          echo "Codecov: Action complete. Check codecov_ats folder for results."
          cat codecov_ats/result.json
        else
          echo "Codecov: Action failed to successfully run"
          exit 1;
        fi
      shell: bash
      env:
        INPUTS_CODECOV_STATIC_TOKEN: ${{ inputs.static_token }}
        INPUTS_CODECOV_TOKEN: ${{ inputs.token }}
        INPUTS_ENTERPRISE_URL: ${{ inputs.enterprise_url }}
        INPUTS_LABEL_MAX_WAIT_TIME: ${{ inputs.label_max_wait_time }}
        INPUTS_OVERRIDE_BASE_COMMIT: ${{ inputs.override_base_commit }}
        INPUTS_OVERRIDE_BRANCH: ${{ inputs.override_branch }}
        INPUTS_OVERRIDE_COMMIT: ${{ inputs.override_commit }}
        INPUTS_OVERRIDE_PARENT: ${{ inputs.override_parent }}
        INPUTS_OVERRIDE_PR: ${{ inputs.override_pr }}
        INPUTS_OVERRIDE_SLUG: ${{ inputs.override_slug }}
        INPUTS_STATIC_FOLDERS_TO_EXCLUDE: ${{ inputs.static_folder_to_exclude }}
        INPUTS_STATIC_FOLDER_TO_SEARCH: ${{ inputs.static_folder_to_search }}
        INPUTS_STATIC_FORCE: ${{ inputs.static_force }}
        INPUTS_STATIC_NUMBER_PROCESSES: ${{ inputs.static_number_processes }}
        INPUTS_STATIC_SEARCH_PATTERN: ${{ inputs.static_search_pattern }}
        INPUTS_VERBOSE: ${{ inputs.verbose }}
