name: Workflow for Codecov Action
on: [push, pull_request]

defaults:
  run:
    # the default default is:
    #      bash --noprofile --norc -eo pipefail {0}
    # Helps with debugging
    shell: bash --noprofile --norc -eo pipefail -ux {0}

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [macos-latest, windows-latest, ubuntu-latest]
        os: [macos-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0
        with:
          fetch-depth: 0
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install python dependencies
        run: pip install -r app/requirements.txt
      - name: Run ATS
        uses: ./
        with:
          folders_to_exclude: node_modules
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          CODECOV_STATIC_TOKEN: ${{ secrets.CODECOV_STATIC_TOKEN }}
      - name: Run Tests and collect coverage (if there are tests to run)
        run: |
          length_of_tests=$(cat codecov_ats/tests_to_run.json | jq 'length')
          # The 1st value doesn't count, it's '--cov-context=test' (hence -gt 1)
          if [ $length_of_tests -gt 1 ]; then
            echo "Running $length_of_tests tests"
            # --raw-output0 doesn't work.
            cat codecov_ats/tests_to_run.json | jq 'join("\u0000")' --raw-output | tr -d '\n' | xargs -r0 pytest --cov app
          else
            echo "No tests to run"
          fi
      - name: Upload to Codecov
        uses: codecov/codecov-action@v4-beta
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          flags: smart-tests
          plugins: pycoverage,compress-pycoverage

  test-and-covererage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [macos-latest, windows-latest, ubuntu-latest]
        os: [macos-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0
        with:
          fetch-depth: 0
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: head
      - name: Install bashcov gem
        run: |
          gem install bashcov
          gem install simplecov
          gem install simplecov-cobertura
      - name: Run ATS
        run: bashcov ./src/codecov_ats.sh
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          CODECOV_STATIC_TOKEN: ${{ secrets.CODECOV_STATIC_TOKEN }}
          INPUTS_VERBOSE: true
      - name: Upload to Codecov
        uses: codecov/codecov-action@v4-beta
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          flags: bash
