name: Workflow for Codecov Action
on: [push, pull_request]
jobs:
  no-deps:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0
      - name: Upload coverage to Codecov (script)
        uses: ./
        with:
          static_token: ${{ secrets.CODECOV_STATIC_TOKEN }}
          token: ${{ secrets.CODECOV_ORG_TOKEN }}
          verbose: true
      - name: Upload coverage to Codecov (demo)
        uses: ./
        with:
          static_token: ${{ secrets.CODECOV_STATIC_TOKEN }}
          token: ${{ secrets.CODECOV_ORG_TOKEN }}
          verbose: true
      - name: Upload coverage to Codecov (version)
        uses: ./
        with:
          fail_ci_if_error: true
          static_token: ${{ secrets.CODECOV_STATIC_TOKEN }}
          token: ${{ secrets.CODECOV_ORG_TOKEN }}
          verbose: true
          version: v0.2.2
      - name: Upload to Codecov
        uses: codecov/codecov-action@v4-beta
        with:
          version: v0.2.2
        env:
          token: ${{ secrets.CODECOV_ORG_TOKEN }}
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Run tests and collect coverage
        run: npm run test
      - name: Upload coverage to Codecov (script)
        uses: ./
        with:
          static_token: ${{ secrets.CODECOV_STATIC_TOKEN }}
          token: ${{ secrets.CODECOV_ORG_TOKEN }}
          verbose: true
      - name: Upload coverage to Codecov (demo)
        uses: ./
        with:
          static_token: ${{ secrets.CODECOV_STATIC_TOKEN }}
          token: ${{ secrets.CODECOV_ORG_TOKEN }}
          verbose: true
      - name: Upload coverage to Codecov (version)
        uses: ./
        with:
          fail_ci_if_error: true
          static_token: ${{ secrets.CODECOV_STATIC_TOKEN }}
          token: ${{ secrets.CODECOV_ORG_TOKEN }}
          verbose: true
          version: v0.2.2
      - name: Upload to Codecov
        uses: codecov/codecov-action@v4-beta
        with:
          version: v0.2.2
        env:
          token: ${{ secrets.CODECOV_ORG_TOKEN }}
