name: Workflow for Codecov Action
on: [push, pull_request]
jobs:
  no-deps:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [macos-latest, windows-latest, ubuntu-latest]
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install python dependencies
        run: pip install -r app/requirements.txt
      - name: Run ATS (script)
        uses: ./
        with:
          fail_ci_if_error: true
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}
          CODECOV_STATIC_TOKEN: ${{ secrets.CODECOV_STATIC_TOKEN }}

  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [macos-latest, windows-latest, ubuntu-latest]
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0
        with:
          fetch-depth: 0
      - name: Echo things
        run: |
          echo $(git rev-parse HEAD^)
          echo ${{ github.context.payload.pull_request }}
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Run tests and collect coverage
        run: npm run test
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install python dependencies
        run: pip install -r app/requirements.txt
      - name: Run ATS
        uses: ./
        with:
          fail_ci_if_error: true
          folders_to_exclude: node_modules
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}
          CODECOV_STATIC_TOKEN: ${{ secrets.CODECOV_STATIC_TOKEN }}
      - name: Run Tests and collect coverage
        run: pytest --cov app ${{ env.CODECOV_ATS_TESTS_TO_RUN }}
      - name: Upload to Codecov
        uses: codecov/codecov-action@v4-beta
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}
